version: 2
jobs:
  compilar:
    docker:
      - image: circleci/node:12.16.1-stretch-browsers
    steps:
      - checkout
      - run:
          name: Instalando dependencias de pilas
          command: make iniciar
      - run:
          name: Ejecutando test
          command: make test
  binarios:
    docker:
      - image: circleci/node:12.16.1-stretch-browsers
    steps:
      - checkout
      - run: make iniciar
      - run: make test
      - run: echo "Instalando wine ..."
      - run: sudo dpkg --add-architecture i386 && sudo apt update
      - run: sudo apt install wine wine32 wine64 libwine libwine:i386 fonts-wine
      - run: make binarios
      - run: sudo apt install texlive-latex-extra
      - run: wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb; sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb; rm pandoc-2.9.2.1-1-amd64.deb
      - run: echo "Instalando go y ghr ..."
      - run: sudo apt-get install golang
      - run: wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz; tar -xvf go1.10.3.linux-amd64.tar.gz; sudo mv go /usr/local
      - run: GOPATH="/tmp/go" GOROOT=/usr/local/go /usr/local/go/bin/go get github.com/tcnksm/ghr
      - run: echo "Subiendo binarios"
      - run: /tmp/go/bin/ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` binarios/
      - run: echo "Generando manuales..."
      - run: sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
      - run: make pilas_manuales_descargables
      - run: /tmp/go/bin/ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace `git describe --tags` manuales/
  actualizar-sitio:
    docker:
      - image: circleci/node:12.16.1-stretch-browsers
    steps:
      - checkout
      - run: make iniciar
      - run: make test
      - run: echo -e "Host hugoruscitti.com.ar\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: "Realizando deploy a dokku producción ..."
          command: make deploy_a_dokku
  actualizar-sitio-dev:
    docker:
      - image: circleci/node:12.16.1-stretch-browsers
    steps:
      - checkout
      - run: make iniciar
      - run: make test
      - run: echo -e "Host hugoruscitti.com.ar\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: "Realizando deploy a dokku desarrollo ..."
          command: make deploy_a_dokku_dev
workflows:
  version: 2
  compilar-y-subir:
    jobs:
      - compilar
      - actualizar-sitio-dev
      - binarios:
          filters:
            tags:
              only: /^v\d+.\d+.\d+/
            branches:
              ignore: /.*/
      - actualizar-sitio:
          filters:
            tags:
              only: /^v\d+.\d+.\d+/
            branches:
              ignore: /.*/
